### ISSUE TITLE
Create palletts

### ISSUE THREAD

**Issue by thundergreen** [doctormord/Responsive_LED_Control#11]
Hi.. I successfuly installed your ino on my esp8266. Everything works perfectly. Now I was wondering how to create own palletts.. as i have a specific plan in my head :)

**Comment by mungle** [comment]
Yes please, could you give me some input as well? I tried to use the python script but I'm getting errors al "infile = sys.argv[1]" line...

Any easy step by step guide it will be appreciated... thank you!

**Comment by doctormord** [comment]
I used the palettes from "cpt-city" like introduced here:
http://fastled.io/tools/paletteknife/

Using the bookmark-js-code on Chrome or Safari (Firefox is not working correctly).

The example palette from here:
http://soliton.vm.bytemark.co.uk/pub/cpt-city/rc/tn/purplefly.png.index.html

gives the following Code:
```
// Gradient palette "purplefly_gp", originally from
// http://soliton.vm.bytemark.co.uk/pub/cpt-city/rc/tn/purplefly.png.index.html
// converted for FastLED with gammas (2.6, 2.2, 2.5)
// Size: 16 bytes of program space.

DEFINE_GRADIENT_PALETTE( purplefly_gp ) {
    0,   0,  0,  0,
   63, 239,  0,122,
  191, 252,255, 78,
  255,   0,  0,  0};
```
Paste this into a text file and run the Pythonscript from
**Responsive_LED_Control/palette_convert/palette_convert.py**
in the same directory like
```python palette_convert.py textfile.txt```

This should give out a workin .bin
