### ISSUE TITLE
http://ledcontrol-1cb0.local/edit produces "File Not Found"

### ISSUE THREAD

**Issue by gregsvo** [doctormord/Responsive_LED_Control#13]
I got the endpoint working, but when I connect to the ESP, I only get "FileNotFound" no "file browser" as the docs say should be there. Logs:

```
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 3
*WM: IP Address:
*WM: 10.0.0.15
connected...yeey :)
OTA Ready
IP address: 10.0.0.15
Open http://LEDCONTROL-1cb0.local/edit to see the file browser

Palette count: 0
handleFileRead: /edit.htm
```

Thanks for your patience, I'm new to Arduino/esp8266!

**Comment by mungle** [comment]
Hi!
visit http://LEDCONTROL-1cb0.local/upload then try to upload edit.htm from the folder "upload these via file mgr to ESP8266"...

**Comment by gregsvo** [comment]
Thanks, I'll give it a try!
