### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by singaevskiy** [doctormord/Responsive_LED_Control#14]
Hello! I get an error when compiling "C:\Users\1\Documents\Arduino\libraries\FastLED/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output" and the tape does not work, and on McLighting everything works.

**Comment by pmm26** [comment]
with works even with the warning. I chose pin 4 on the code but it was coming out on D4

**Comment by doctormord** [comment]
`"C:\Users\1\Documents\Arduino\libraries\FastLED/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined. All SPI access will default to bitbanged output"`

is not an issue.
