### ISSUE TITLE
Palette operations cause reboot

### ISSUE THREAD

**Issue by ke5** [doctormord/Responsive_LED_Control#15]
Hi.
Great project, thanks for the hard work!
I'm getting a stack dump(?) and reboot any time I choose a palette operation (example output below - I don't know what it means or what to do with it). I've tried using a few different NodeMCU boards and this morning, a Wemos D1 Mini. I've uploaded the 'extra' files using the /edit method and the ESP8266 Sketch Data Upload utility - both with the same outcome.
As far as I can tell I've followed all the instructions, including the FastLED patch, correctly.
Can anyone help?
Thanks again, Kevin

Crash output follows --->

Exception (28):
epc1=0x40221800 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: cont 
sp: 3fff2260 end: 3fff2790 offset: 01a0

>>>stack>>>
3fff2400:  00000000 400042db 00000019 ffffffff  
3fff2410:  40004b31 3fff2460 00000004 0030f82c  
3fff2420:  3ffe8308 00000000 00000020 40100ec6  
3fff2430:  3ffeb252 3ffe910b 3ffee9c0 3fff2460  
3fff2440:  00000001 401034c7 3ffef418 3ffe9120  
3fff2450:  00000000 3ffe8308 3fff2500 4022035c  
3fff2460:  00000000 ffffffff 00000000 00000000  
3fff2470:  00000000 00000013 00302073 0030f800  
3fff2480:  40004b31 3fff4a9c 00000100 00310200  
3fff2490:  40105acc 3fff4eec 00000100 3fff4eec  
3fff24a0:  0010698d 3fff4a9c 00000100 3fff4a9c  
3fff24b0:  4021769d 0030f800 00000000 40217692  
3fff24c0:  3fff2630 3fff2600 0000000c 4021a0e0  
3fff24d0:  3ffe911f 00000013 00000019 ffffffff  
3fff24e0:  3fff4a9c 00000100 3fff32b0 3fff16a8  
3fff24f0:  3fff16a8 3ffe8308 00000040 4021dd3d  
3fff2500:  3fff25c3 00310200 0000002c ffff0208  
3fff2510:  3fff25b0 0000003f 00000000 3fff4a9c  
3fff2520:  00000000 000000f8 000007f0 61702f01  
3fff2530:  7474656c 332f7365 6c625f35 3fff49e0  
3fff2540:  00000102 00010200 3fff32b0 4020387c  
3fff2550:  00000018 3fff6d3c 00000018 00300000  
3fff2560:  00000008 00000002 00000000 80085d00  
3fff2570:  3fff49dc 00000008 3fff6564 4021dd80  
3fff2580:  3fff2630 3fff2600 00000008 40205c38  
3fff2590:  3fff00f8 00000000 3fff32b0 3fff2650  
3fff25a0:  3fff4774 00000000 00000009 40217c70  
3fff25b0:  64616f4c 6c617020 65747465 6d616e20  
3fff25c0:  3f206465 00000018 3fff6224 40100690  
3fff25d0:  3fff1680 0000047b 0000047b 4010020c  
3fff25e0:  000007f0 00000001 3fff5094 40100690  
3fff25f0:  3fff2630 3fff2600 00000008 40219244  
3fff2600:  000007f0 00000003 00000000 000007f0  
3fff2610:  3fff4ff0 ffffffff 3fff5094 4021a46c  
3fff2620:  3ffe910b 00000001 3fff2600 3fff2630  
3fff2630:  3fff4ff4 3fff5094 00000000 3fff16a8  
3fff2640:  000007f0 00000001 3fff6564 4020a425  
3fff2650:  3ffea550 00000000 000003e8 40100690  
3fff2660:  00000000 00000000 00000000 00000000  
3fff2670:  3fff122c 00000002 00000001 402186bc  
3fff2680:  b0ff0101 000003f0 00000000 00000001  
3fff2690:  3fff122c 3fff128d 00000000 4020a4f3  
3fff26a0:  3fff1298 00000028 000003e8 3fff1768  
3fff26b0:  3fff0b40 3fff0aac 3fff1150 4020a561  
3fff26c0:  3fff0f20 000000b4 4021930c 3fff1770  
3fff26d0:  3fff0f20 3fff0b64 00000000 402013e3  
3fff26e0:  4020cb24 3fff0b64 3fff0f20 40216e24  
3fff26f0:  4024ce6a 0011f783 3fff1470 00000001  
3fff2700:  4024dfef 3fff1768 4021930c 3fff1770  
3fff2710:  3fff2d94 4020d7f0 3fff0aac 3fff1768  
3fff2720:  3fff0b40 3fff0aac 3fff1150 4020a889  
3fff2730:  00000000 00000000 402075ac 00000000  
3fff2740:  00000000 00000000 feefeffe feefeffe  
3fff2750:  00000000 3fff0b38 feefeffe feefeffe  
3fff2760:  00000000 00000000 00000001 3fff1768  
3fff2770:  3fffdad0 00000000 3fff1761 40219358  
3fff2780:  feefeffe feefeffe 3fff1770 40100710  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v4ceabea9
~ld

**Comment by ke5** [comment]
`Exception 28: LoadProhibited: A load referenced a page mapped with an attribute that does not permit loads
Decoding 39 results
0x40221800: memchr at /Users/igrokhotkov/e/newlib-xtensa/xtensa-lx106-elf/newlib/libc/string/../../../.././newlib/libc/string/memchr.c line 128
0x4010698d: __wrap_spi_flash_read at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/core_esp8266_phy.c line 267
0x4021769d: EspClass::flashRead(unsigned int, unsigned int*, unsigned int) at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/Esp.cpp line 514
0x4022035c: _svfprintf_r at /Users/igrokhotkov/e/newlib-xtensa/xtensa-lx106-elf/newlib/libc/stdio/../../../.././newlib/libc/stdio/nano-vfprintf.c line 641
0x40105acc: spi_flash_read at ?? line ?
0x4021769d: EspClass::flashRead(unsigned int, unsigned int*, unsigned int) at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/Esp.cpp line 514
0x40217692: EspClass::flashRead(unsigned int, unsigned int*, unsigned int) at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/Esp.cpp line 511
0x4021a0e0: spiffs_hal_read(unsigned int, unsigned int, unsigned char*) at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/spiffs_hal.cpp line 67
0x40202550: spiffs_read_dir_v at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/spiffs/spiffs_hydrogen.c line 1122
0x4021dd3d: _vsnprintf_r at /Users/igrokhotkov/e/newlib-xtensa/xtensa-lx106-elf/newlib/libc/stdio/../../../.././newlib/libc/stdio/vsnprintf.c line 73
0x4020387c: spiffs_page_data_check at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/spiffs/spiffs_nucleus.c line 1164
0x4021dd80: vsnprintf at /Users/igrokhotkov/e/newlib-xtensa/xtensa-lx106-elf/newlib/libc/stdio/../../../.././newlib/libc/stdio/vsnprintf.c line 42
0x40205c38: spiffs_object_read at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/spiffs/spiffs_nucleus.c line 2037
0x40217c70: Print::printf(char const*, ...) at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/Print.cpp line 205
0x40100690: free at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/umm_malloc/umm_malloc.c line 1737
0x4010020c: _umm_free at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/umm_malloc/umm_malloc.c line 1291
0x40100690: free at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/umm_malloc/umm_malloc.c line 1737
0x40219244: operator delete(void*) at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/abi.cpp line 57
0x4021a46c: std::__shared_count(__gnu_cxx::_Lock_policy)0>::~__shared_count() at /Users/kev/Library/Arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/1.20.0-26-gb404fb9-2/xtensa-lx106-elf/include/c++/4.8.2/bits/shared_ptr_base.h line 547
0x4020a425: loadPaletteFromFile(int, CRGBPalette16*) at /var/folders/7q/51klsbzn1jj3hvw0587nlym40000gn/T/arduino_build_304966/sketch/colormodes.h line 256
0x40104ee9: ets_timer_disarm at ?? line ?
0x402186bc: random(long) at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/WMath.cpp line 45 (discriminator 1)
0x4020a4f3: ChangePalettePeriodically(bool) at /var/folders/7q/51klsbzn1jj3hvw0587nlym40000gn/T/arduino_build_304966/sketch/colormodes.h line 256
0x4020a561: palette_anims() at /var/folders/7q/51klsbzn1jj3hvw0587nlym40000gn/T/arduino_build_304966/sketch/colormodes.h line 256
0x4021930c: esp_yield at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/core_esp8266_main.cpp line 57
0x402013e3: delay at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/core_esp8266_wiring.c line 51
0x4020cb24: CPixelLEDController(EOrder)66, 1, 4294967295u>::show(CRGB const*, int, CRGB) at /var/folders/7q/51klsbzn1jj3hvw0587nlym40000gn/T/arduino_build_304966/sketch/colormodes.h line 256
0x40216e24: WebSocketsServer::handleClientData() at /Users/kev/Documents/Arduino/libraries/arduinoWebSockets/src/WebSocketsServer.cpp line 153
0x4024ce6a: wifi_get_opmode at ?? line ?
0x4024dfef: wifi_station_get_connect_status at ?? line ?
0x4021930c: esp_yield at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/core_esp8266_main.cpp line 57
0x4020d7f0: ESP8266WiFiSTAClass::status() at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/libraries/ESP8266WiFi/src/ESP8266WiFiSTA.cpp line 548
0x4020a889: loop at /var/folders/7q/51klsbzn1jj3hvw0587nlym40000gn/T/arduino_build_304966/sketch/colormodes.h line 256
0x402075ac: _M_invoke at /var/folders/7q/51klsbzn1jj3hvw0587nlym40000gn/T/arduino_build_304966/sketch/colormodes.h line 256
0x40219358: loop_wrapper at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/core_esp8266_main.cpp line 57
0x40100710: cont_norm at /Users/kev/Library/Arduino15/packages/esp8266/hardware/esp8266/2.4.0/cores/esp8266/cont.S line 109`

**Comment by bombcheck** [comment]
Having the same issue...

**Comment by doctormord** [comment]
I haven't had this issues with the palette files i have included but i only tested it with Wemos D1 Mini.

Could you test it without any LEDs attached?

Regards,

Christian

**Comment by bombcheck** [comment]
It crashes even without a led attached.

**Comment by doctormord** [comment]
Fixed, see changelog.
