### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by bombcheck** [doctormord/Responsive_LED_Control#16]
Reboots often when using the web ui. Seems to happen mostly when initiating the ws connect... Any idea?

**Comment by bombcheck** [comment]
It throws: Exception 28

**Comment by bombcheck** [comment]
Hm think it has to do with "palettes" directory: When it is there with a file in it, it seems stable...

**Comment by doctormord** [comment]
Does the palette animations work as well without any issues?

**Comment by bombcheck** [comment]
No, they keep crashing the system or simply do not work.

**Comment by doctormord** [comment]
Hmm, i have no clue at the moment. Could you try to fully erase the flash and then reuploaded everything?

I wonder if it works if you set the max_current to a very low value or when having no lights connected.

**Comment by bombcheck** [comment]
Clean flash makes no difference. Checked the palette-functions: We should check if files/dir exists before we try to use them...

**Comment by doctormord** [comment]
But if the animations don't work with the provided palette-files, the issue/problem must be somewhere else, i'd guess.

"I wonder if it works if you set the max_current to a very low value or when having no lights connected."?

**Comment by bombcheck** [comment]
Will try with a low current setting. But why this should have any effect?

**Comment by bombcheck** [comment]
Sorry, accidentally closed it.

**Comment by doctormord** [comment]
Their might be a problem with the supply if the allowed max_current is higher than what the supply can provide. Easiest way is to test without LEDs connected.

**Comment by bombcheck** [comment]
Ah OK. But available power is not a problem in my setup. :)

**Comment by bombcheck** [comment]
OK, if no "palettes" dir is there, it crashes very very often. Upload at least one palette-file in the dir and it runs stable. But it crashes every time when trying to activate the palette animation feature. Uploaded some more files but issue persists. Crashes when clicking "next" or "previous" palette animation controls.
Compiled for ESP-12E, 80 MHz, 4M (1M SPIFFS), IwIP v2

**Comment by TailoredTuna** [comment]
Have this issue as well. All files were uploaded fine. as soon as you click on palette animation it crashes with exception 28. Using D1 Mini's with 4M flash, set SPIFFS to 2M. Any ideas?

**Comment by TailoredTuna** [comment]
Further more... Settings the number of LEDs or Current crashes with excpt 28, and so does doing just about anything else.. at one point (only one time in the tons of crashes) I even got a CRC error. Tried this on multiple D1 Mini's. Other LED projects work fine, dont think its hardware..

"Load settings.Settings CRC failed on read from EEPROM"

**Comment by doctormord** [comment]
Have you tried resetting all settings including eeprom? I don't have any of these problems running SPIFFS at 3M (or 1?) and 160MHz clock speed.

**Comment by JPluess** [comment]
hello guys, it looks lovely but it keeps crashing a lot. i have not uploaded all pallets so pressing that pallet button or setting current/lednums will make it crash. 
i had the mc lighting installed on spiffs before. maybe since there were the old files on spiffs it would not  boot right and crah. i fixed that with an empty format spiffs sketch. And reuploaded yours after.

**Comment by doctormord** [comment]
Interesting workaround, i also have issue with crashing when selecting a palette in the actual build. Dunno actually what is the cause. :(

**Comment by doctormord** [comment]
Fixed the issue, see changelog.
