### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Malle355** [doctormord/Responsive_LED_Control#2]
Hi my friend,

I want to use your Project. First I used MCLightning and now I want to use yours.

I got an error at compiling. Dont know why. Can you help?

![unbenann4t](https://user-images.githubusercontent.com/1338236/31050237-01a199da-a645-11e7-94fe-a0c5ec946732.PNG)

**Comment by doctormord** [comment]
Hi,

you'll need to have WifiManager installed as well:
https://github.com/tzapu/WiFiManager

**Comment by Malle355** [comment]
Yeah WifiManager is installed. I added it with the Library Manager in the Arduino IDE. I also tried to download it via Github but with no success.

I completely deleted Arduino IDE and all Libraries. But still it did not work. To Upload MC Lightning is no problem and it also using WifiManager.

**Comment by doctormord** [comment]
Well, then RemoteDebug might be missing?

https://github.com/JoaoLopesF/ESP8266-RemoteDebug-Telnet

**Comment by Malle355** [comment]
Nah everything seems working fine.

![unbenannt3](https://user-images.githubusercontent.com/1338236/31091605-e0c0e960-a7ab-11e7-8964-ed56f127100f.PNG)
![unbenannt4](https://user-images.githubusercontent.com/1338236/31091606-e0daf134-a7ab-11e7-92ba-1fce1a2bde36.PNG)

Maybe I miss something.

Thank you really much.


Edit: I tried to compile a Example Sketch from RemoteDebug and there is no problem with compiling.

**Comment by Malle355** [comment]
Ok. I am really sorry. I just re-downloaded the complete Branch and now it is working. I dont know why its now working. Maybe there was a corrupt file while downloaded. If you read it you can close the Topic now. Thank you so much for your help.

Greetings.

**Comment by doctormord** [comment]
Good to hear it is working now. :-)

Best regards, Christian
