### ISSUE TITLE
Random flickering

### ISSUE THREAD

**Issue by emoryy** [doctormord/Responsive_LED_Control#5]
Hello!
I've just tried this, but i'm experiencing some random flickering when playing patterns.
See this video, showing the patterns "TV" and "Sinelon": https://photos.app.goo.gl/wuknWqT7Q6xfnSp42
Using a D1 Mini, and an Adafruit Neopixel ring.
And no, the glitter function is not on.
I don't see this with McLighting at all.

**Comment by doctormord** [comment]
Cheers,

McLightning is a bit different in dealing with the leds. How many LEDs did you setup? Maybe it is an signal reflection due to wrong LED count. I'm using a 100R series resistor between my Leds and the D1 mini. It that doesn't help, you may try commenting out "yield()" the sheet.

Regards,

Christian

**Comment by emoryy** [comment]
Thanks for the quick answer! I did have setup 16 LEDs since this Neopixel ring has 16 of them. I've just tried putting a 100Ω resistor between the data pin of the D1 mini and the data in of the ring, but it didn't change anything.

**Comment by doctormord** [comment]
Hi,

i now tried with a noname 12 LED ring but can't reproduce the problem. I don't see any flickering. The D1 Mini is powered by my computers USB-Port. Wire length is about 15cm, no series resistor, no other changes to the sketch.

**Comment by emoryy** [comment]
At the moment I strongly suspect that the issue is with the FastLED library. I guess I'll escalate the issue to them.

**Comment by doctormord** [comment]
I'm using FastLED 3.1.6 with this sketch.
