### ISSUE TITLE
Error Compiling for board WeMos D1 R2 & Mini

### ISSUE THREAD

**Issue by Rekcuf97** [doctormord/Responsive_LED_Control#7]
i get this error when trying to upload into the WeMos board.
Any fix?

**Comment by Rekcuf97** [comment]
Arduino: 1.8.5 (Windows 10), Board: "WeMos D1 R2 & mini, 80 MHz, 921600, 4M (3M SPIFFS)"

C:\Users\MyITX\Desktop\PC lightings\Responsive_LED_Control-master\Responsive_Led_Control\Responsive_Led_Control.ino:39:69: fatal error: RemoteDebug.h: No such file or directory

 #include "RemoteDebug.h" //https://github.com/JoaoLopesF/RemoteDebug

                                                                     ^

compilation terminated.

exit status 1
Error compiling for board WeMos D1 R2 & mini.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by eLement87** [comment]
You must add the required librarys to your Arduino IDE.

In this case you have to add the RemoteDebug library from https://github.com/JoaoLopesF/RemoteDebug

After this, you're probable to compile the sketch.
