### ISSUE TITLE
Problem with palettes

### ISSUE THREAD

**Issue by superpat999** [doctormord/Responsive_LED_Control#9]
Just built system on Wemos D1, 3M flash size.  All appears OK  with web pages apart from palettes. The  serial monitor shows when "pressing" next palette button on CGI:-

Current pallet_ndx=0
Error, unable to open palette
Error loading paletteFile at index -1
Next palette: -1
WS: [1] get Text: =all
Activated mode [2]!
WS: [1] get Text: =palette_anims
Activated mode [9]!
Unable to allocate memory for palette
New pallet index: 0
Unable to allocate memory for palette
New pallet index: 0

When building s/w, I could not upload the palette directory in one go, I had to upload all the bin files individually. So I  do not know if they went into /palettes on the ESP8266

Please can you suggest how to fault find this

  many thanks

Patrick 

_ _

**Comment by doctormord** [comment]
You will have to create the /palettes folder within the /edit file editor, then upload the palettes into this folder. The error message shows that no palette file is found.

**Comment by superpat999** [comment]
Hi Christian

I have tried to use the /edit file, I enter /palettes in the box on the 
top line of /edit and press create but /palettes does not get created.

I am obviously doing this command incorrectly, please can you give me 
some idea how to enter this command

many thanks

regards

Patrick

**Comment by hugofant** [comment]
Hi Patrick,
choose a palette file first, then write "/palettes" into the field before the filename and press "create" - for the others then you can use "upload".
br
Roman
